debtcollective/dispute-tools

.circleci/config.yml
lib/assets/document_templates/private_student_loan_dispute_letter/defaulted.pug
scripts/install_ghostscript_debian
services/renderers/tool-configurations/private-student-loan-dispute-letter.js
tests/unit/services/renderTests.js
tests/utils/index.js

Also adds a dependency on ghostscript to the test suite for reading the text contents of the rendered pdf letters back so we can verify their contents to prevent these bugs in the future.

 Fix agency address rendering defaulted private student dispute letter

---

models/DisputeStatus.js
tests/unit/models/DisputeStatus.js

The form-data returned is either `'on'` or `'off'`, but this seems to vary so if it's a boolean value we'll let it be whatever it was set to.

Fix sending emails when admins mark to notify the users

---

config/middlewares.js
middlewares/https.js
tests/integration/middlewares/httpsTest.js

This PR adds https redirection as a middleware. We redirect only when running the app in production mode

redirect to https when not running in development mode

---

config/RouteMappings.js
controllers/HomeController.js
middlewares/https.js
tests/integration/middlewares/httpsTest.js

This PR adds a `/health-check` endpoint to be used by ELB (Elastic Load Balancer) to know if the service is running. This endpoint can't have a redirection because health checks don't follow redirects, so we are excluding this endpoint in the HTTPS redirection middleware

/health-check endpoint

---

src/javascripts/components/admin/disputes/AdminShowFormInformationPanel.vue
views/admin/disputes/index.pug

I already updated the search method before to return the intersection of disputes joined with the user and the users matching the Discourse active user search which searches by username, email and IP address. The readable ids were also taking up a lot more room than they needed on the table so this squishes them in a bit to make room for longer names.

Update name search to match what discourse filters by

---

controllers/DisputesController.js
src/javascripts/_entries/admin/disputes/show.js
src/stylesheets/_entries/admin/disputes/show.css

Also addresses small bug in the admin dispute form where variably required fields would show up all the time regardless of the status of their dependent field.

Re-render dispute if render is stale; Fix admin disptue form variably required fields 

---

shared/enum/DisputeStatuses.js
src/stylesheets/components/Modal.css
tests/integration/controllers/DisputesControllerTest.js
tests/unit/models/DisputeStatus.js
views/includes/header.pug
views/layouts/admin.pug
views/layouts/shared.pug

Also addresses several bugs and adds the dispute backoffice to the dropdown if the user is an administrator
**Bugs addressed**
1. The code to load up Vue and the header scripts was missing from the admin and shared layouts, making the header not appear for those layouts.
2. The header was not displaying a dispute administration link
3. A CSS variable was misnamed `text_1` instead of `text-1`

Add more dispute statuses

---

.gitignore
README.md
config/RouteMappings.js
config/config.sample.js
config/middlewares.js
controllers/HomeController.js
lib/data/form-definitions/validations.js
views/admin/disputes/index.pug
views/includes/header.pug
yarn.lock

This PR makes some changes to the header glue so it works for the dispute tools. Also, adds some information on how to configure Discourse to work with SSO
Changes:
* `/login` now respond to get instead of post
* `redirectTo` param removed from `/login`, login endpoint is fixed in the header component
* Getting currentUser correctly in `header.pug`
* Moving the **Admin** link to be a navigation link.
This is currently deployed to tools.debtsyndicate.org

making header login/logout work correctly

---

.gitignore
package.json
src/javascripts/components/admin/disputes/AdminShowFormInformationPanel.vue
src/javascripts/components/disputes/Information.js
src/stylesheets/_entries/disputes/show.css
views/includes/disputes/information-form.pug
views/includes/disputes/information.pug
views/mixins/dispute-tools/form-element.pug
yarn.lock

This PR adds file size validation for attachments in Disputes
[![gif](http://recordit.co/ZiF2kY61Sg.gif)](http://recordit.co/ZiF2kY61Sg)
Also, improves the style of the forms 
**Before**
**After**
Closes https://github.com/debtcollective/parent/issues/150

limiting attachment size to 6mb, improving form styles

---

controllers/DisputesController.js
lib/data/form-definitions/shared-fields/debtAmount.js
lib/data/form-definitions/shared-fields/privacyRelease.js
lib/data/form-definitions/validations.js
models/Dispute.js
package.json
src/javascripts/components/ConfirmInline.js
src/javascripts/components/disputes/CurrencyInput.vue
src/javascripts/components/disputes/DebtAmounts.vue
src/javascripts/components/disputes/InformationForm.js
src/stylesheets/components/ConfirmInline.css
yarn.lock

Resolves the issues brought up in https://github.com/debtcollective/parent/issues/169
@annlarson Please confirm that the updated text for the privacy release is good to go or let me know if there are any changes y'all would like to make to it
No demo for the SSN because it's just an update to the regex pattern for it. Basically you'll be able to input anything that starts and ends with a number and contains exactly nine numbers but can have any other junk in between. That means all the following will be valid inputs that we can handle on the backend:
- `123-33-1234`
- `1-2-3-2-2-1-2-3-4`
- `1 2 3 2 2 1 2 3 4`
- `111 33 4444`
- `111.44_______444_______4`
etc...

Masked currency inputs, more lax SSN patterns, reword privacy release questions

---

views/mixins/dispute-tools/sidebar.pug

https://github.com/debtcollective/parent/issues/172
There is a slight functionality change. The user has to complete the steps in sequence and can't jump ahead. The user can go back to edit previous steps.

disallow skipping steps in the dispute process

---

src/javascripts/components/disputes/Information.js
src/javascripts/components/disputes/InformationForm.js
views/admin/disputes/index.pug

https://github.com/debtcollective/parent/issues/147
Looking at the code, the button was actually supposed to deactivate the dispute in addition to closing the form. I made it do that again. I changed the button text to make that clearer.

Fix Exit form button

---

middlewares/locals.js
models/Dispute.js
src/javascripts/components/disputes/DebtAmounts.vue
src/javascripts/components/disputes/InformationForm.js
src/stylesheets/components/dispute-tools/TextModal.css
src/stylesheets/utils.css
views/disputes/my.pug

This PR makes any dispute queries filter out deactivated disputes by default except when searching by 
dispute id https://github.com/debtcollective/parent/issues/180

don't show deactivated disputes

---

.eslintrc.js
controllers/HomeController.js
src/javascripts/components/Common.js
views/includes/footer.pug

Removed the no-prototype-builtins because it's kind of ridiculous, we never use any objects who don't eventually have Object in their prototype chains 🙄

Open donate modal when query string is passed

---

controllers/SessionsController.js
seeds/20171113114842_dispute_tools.js
tests/integration/controllers/SessionsControllerTest.js
views/disputes/my.pug

This PR makes the `/login` endpoint to always redirect to Discourse. Fixes https://github.com/debtcollective/parent/issues/241
Also, fixes some small typos, one in the **Dispute Any Debt in Collections** tool description and other in the My Disputes `/disputes/my` page

Fixing session login

---

controllers/Admin/DisputesController.js
src/javascripts/components/admin/disputes/AdminDisputesAddStatusForm.js
src/stylesheets/_entries/admin/disputes/index.css
src/stylesheets/base_admin.css
views/admin/disputes/index.pug

This PR changes the dispute admin list to show more items per page, from 5 to 25. Also, makes some changes on how we display data on the table so it doesn't have a new line

showing 25 disputes instead of 5 in the admin dispute list

---

views/includes/disputes/follow-up.pug

Refactor conditional inside pug file to always show the Discourse link in the Dispute **Now what** page

always show discourse link in follow-up page

---

package.json
yarn.lock

This PR upgrades `webpack` to 3.12.0 to fix some security issues

upgrading webpack to 3.12

---

config/RouteMappings.js
controllers/DisputeToolsController.js
controllers/SessionsController.js
services/auth/authentication.js
tests/integration/controllers/DisputeToolsControllerTest.js
views/dispute-tools/show-optionless.pug
views/dispute-tools/show.pug
views/shared/400.pug

- Add `redirectTo` functionality to login.
- Adding `startDispute` route, to allow get requests to create a Dispute. This is used with `redirectTo` to allow redirect to a new dispute after login
Closes debtcollective/parent#252
[Video](https://monosnap.com/file/1vS4OBlWbmJ0feG8GUSYp04pmVtgns)

adding startDispute get to redirect after login

---

views/includes/footer.pug

- Removing duplicated "Campaigns" link
- About us points now to landing page

changing footer links

---

controllers/DisputesController.js
models/Dispute.js
shared/enum/DisputeStatuses.js
tests/integration/controllers/DisputesControllerTest.js
tests/unit/models/Dispute.js

This PR adds the **New** status for Disputes, this will be the new default status.
When a User saves some data in the Dispute (either by clicking **Save for later** or by completing a form), we will change the status to **Incomplete** and create the Discourse thread at that moment.
Closes debtcollective/parent#251

'New' status for Disputes, creating discourse thread when the status is Incomplete

---

src/javascripts/components/disputes/InformationForm.js

The current validation flow of our forms used to not run as a cause of a bad way to traverse elements within the form, besides, the flow itself needed some updates in order to handle properly dynamic fields generated in some forms and updates for handle radio inputs properly.
Closes #109 
_As the video is short look for sec 2 where the error is being thrown, besides, notice that despite the error the form is being submitted_
http://recordit.co/cNPvdrP9h8
_Now after the fix_
http://recordit.co/k7JSBGReHw
Another issue that has been solved around this scope is exposed below:
_Before this PR "Dispute your wages being taken" option A throws an error that crash the app if SSN wasn't valid_
http://recordit.co/nYhCSL4c3f
_Now after the fix, it shows error properly_
http://recordit.co/XgKjzKbK7H …

Fix InformationForm validation

---

Makefile
scripts/build

While this still not the ideal case, this code adds a minimal update to the `build` command to allow devs to run build in development mode _(allowing set breakpoints for development process)_
The workflow to develop should be improved by:
- Adding documentation on "How is the inteded workflow for the development of this project"
or
- Add a new webpack configuration in order to allow "typical development workflow" _(Having hot reload and ability to set breakpoints on the application)_

Add optional argument to build script to be able to run in dev mode

---

README.md

Updating Discourse SSO configuration instructions in README to be up to date with the latest version of Discourse.

docs(sso): updating sso configuration instructions

---

src/javascripts/components/DonationFlow.js

As the final preview amount needed to get updated with the user selection, that update used to be made on every change of the view, instead, this code updates the HTML only when the final view is about to get rendered.
Closes #127 
The error described at #127 doesn't provide clear information of the error. In that sense, I haven't been able to reproduce it, nevertheless, the fact of not update the HTML on every render may somehow help to have a better approach and potentially avoid the error.

refactor(DonationFLow): Update HTML for final preview only when view is about to render

---

src/javascripts/lib/widget/Utils.js

Move the getOwnPropertyDescriptor statement to prevent undefined description when using the defineProperty method.
I have tried to reproduce the issue on iPhone using Safari mobile browser and even add tests in order to see if I was able to trigger the issue, nevertheless, I could not reproduce it. On the other hand, the code on this PR will Inevitably prevent the defineProperty signature from failing by making sure all the arguments are defined.

Prevent invalid signature of defineProperty on "mix" function usage

---

views/admin/disputes/index.pug
views/admin/disputes/show.pug
views/dispute-tools/index.pug
views/dispute-tools/show-optionless.pug
views/dispute-tools/show.pug
views/disputes/my.pug
views/disputes/show.pug
views/disputes/showForVisitor.pug
views/home/contact.pug
views/home/index.pug
views/layouts/shared.pug

To attach some JS behavior to views the code currently instantiate classes, those classes should
always be available unless there are some build process error (or something that at this point is
unknown) this code avoid to trigger errors to sentry but instead a friendly notification as if this
happens the problem is likely to be somewhere else.
Closes #113 
Closes #124 
Closes #126

refactor(Views): Add short-circuit evaluation for View class usage

---

lib/data/form-definitions/validations.js
package.json
services/render.js
tests/form-validations/Field.test.js
tests/unit/services/renderTests.js
yarn.lock

The method of getAttributesFromValidations may receive inputs that don't belong to any of the
defined cases within, thus, those cases will throw an unexpected error that makes the whole flow
crash. This commit adds some tests cases to monitor and support unexpected entries.
Closes #117

fix(Field): Prevent fatal error on getAttributesFromValidations

---

src/javascripts/components/disputes/Information.js

This code will keep the confirmation step when a dispute with information is about to get deleted,
but removing the deprecated call to the method _confirmDeactivateDispute as it does no longer exist.
Closes #111

fix(Information): Remove deprecated method usage on _handleDeactivateDispute

---

src/javascripts/components/admin/disputes/AdminDisputesAddStatusForm.js
src/javascripts/components/admin/disputes/AdminDisputesIndexController.js
src/javascripts/components/admin/disputes/ManageDisputeAdmins.vue

Disabling admin assignment until the dispute changes status to prevent admin assignment going out of
sync with Discourse
fix #138
**with dispute thread id**
**without dispute thread id**

fix(Admin): disabling admin assignment for Disputes without a Dispute thread

---

controllers/SessionsController.js

Add extra case whenever the authentication fails without user or error **(Typically invalid signature
when trying to access to callback from SessionController)** for those cases we will send a message to sentry with extra information from executed Strategy and redirect to home avoiding the app to crash.
Closes #122

fix(SessionController): Handle passport.authenticate that resolves without user

---

lib/errors/AuthenticationFailure.js
lib/errors/BadRequest.js
lib/errors/ForbiddenError.js
lib/passport/discourse.js
services/sso.js

Currently, sometimes after click "login" in the dispute tools app and successfully write credentials in Discourse app, the callback from SessionController gets called twice with the same SSO Value which then leads to the second call that throws AuthenticationFailure. 
While being called twice may be a bug to fix, the fact of using the same sso value and report AuthenticationFailure is not, in that sense,  this code will allow to just send a notice to the error monitor about what just happened and keep the "watch" for an exception in case something unexpected happen. 
Ultimately, this code adds some extra properties missing for custom errors to avoid empty errors from being triggered.
Closes #121

Add improvements to error handling and avoid false bug reports

---

lib/data/form-definitions/validations.js
services/formValidation.js
tests/form-validations/Field.test.js

After realize startsWith is not supported with the same signature over IE, the idea is to change to use
indexOf instead. Check comment at https://github.com/debtcollective/dispute-tools/issues/145#issuecomment-464822580
Besides, keep in mind that the cases changed here has their tests and as will be expected they pass successfully.
Closes #145

Replace `startsWith` by `indexOf` for cross browser compatibility

---

views/mixins/dispute-tools/form-element.pug

Before, the computation used to map to "_formData[field.name]" value itself whenever the value of it
weren't string which make impossible to mark unchecked inputs, instead, this code introduces a
consistent way to know if the input should be checked TRUE or FALSE.
Closes #149

fix(form-element): Change computation of checked attribute to always return boolean values

---

lib/data/form-definitions/credit-report-dispute.js
services/formValidation.js
shared/Checkit.js
src/javascripts/components/disputes/InformationForm.js
tests/unit/shared/CheckitTests.js

It is important to understand that we are using an unmaintained library to handle validations, while it is powerful there are some lack of features and documentation, with that being said, currently when a dev create a rule for a field like `["oneOf: <values>", "required"]` we face the following scenario:
- a field may be intended for an array of options, thus, select no options will result on value `[]`
- `[]` is a value which will make the "required" built-in option pass
For the above scenario, we need to explicitly say to our custom rule that: "If the field is required and the value is empty then fail". It is also imperative to understand that the expectations for the rule as it was built is to pass on empty values check https://github.com/debtcollective/dispute-tools/blob/197e4cac47399 …

Allow custom `oneOf` rule to being able to handle required fields

---

.gitlab-ci.yml
services/formValidation.js
tests/documents/credit-report-dispute-letter.test.js
tests/unit/services/renderTests.js

`Array.find` is not available in old browsers, this change fixes two issues we are getting in Sentry.
Also, we are adding the documents command
Fixes #152 
Fixes #157

Using lodash _.find instead of native Array.find

---

views/mixins/dispute-tools/form-element.pug

This PR handles the case when there's no checkbox data. We are assuming that every time we check this we have an Array, but this is not the case.

fix(form-element): handling undefined data case when rendering checkboxes

---

controllers/DisputesController.js
tests/integration/controllers/DisputesControllerTest.js

I'm improving the messages we return when users submit a form without frontend validation. This case shouldn't happen since we require JavaScript for the application to work.
I'm adding a test case for this behavior.
Closes #151

Add test for case when submiting form without frontend validation

---

views/includes/disputes/information-form.pug

.mxn2 is a class that use CSS Variables (like many others) nevertheless, for this case, the class
styles don't load on development because the compilation of the styles seems to not recognize the
syntax or the compilation is simply different, unlike production where the class actually inject the
intended styles and make the form inputs have negative margins.
Removing it from the form children should make the fix for production.
Closes #163

fix(information-form): Remove class that inject undesire negative margin

---

lib/data/form-definitions/credit-report-dispute.js
models/DisputeStatus.js
tests/unit/models/DisputeStatus.js

This method is used in the admin DisputeController and is used to add admin notes to a Dispute.
Since this value can't be changed by an admin, we make sure we keep the last value provided by the
user or default to null.
Fixes #170

fix(DisputeStatus): preserve pendingSubmission value from lastStatus in DisputeStatus.createForDispute

---

.gitlab-ci.yml
models/Dispute.js
package.json
services/messages/DisputeThreadOriginMessage.js
tests/unit/models/Dispute.js

**What:** Add creditor name to Dispute thread title
**Why:** Close #176 
**How:**
- Add `dispute.creditor` method
- Use creditor name when creating the Discourse thread

Add creditor name to Dispute thread title

---

package.json
yarn.lock

**What:** Locking `svg-sprite` version to 1.4.0
**Why:** We used initially the 1.3.3 version, but since the semver range was open to minor updates, the 1.5.0 version was installed and didn't work with our code.
**How:** Locking the version in package.json

fix(package.json): lock svg-sprite dependency to 1.4.0

---

views/messages/CompletedDisputeMessage.md.js

**What:** Escape links from Onebox
**Why:** Onebox is what Discourse uses to expand links they issue we are having is that it tries to expand our Dispute download link and fails because requires a valid session, and uses the SSO link instead. Closes #184 
**How:** By wrapping the link in a blockquote we prevent Onebox from expanding the link.

fix: prevent dispute download links to be expanded by Discourse

---

LICENSE
package.json
services/messages/DiscourseMessage.js
tests/unit/jobs/scheduled/CleanupDisputesTest.js
tests/unit/messages/DisputeThreadOriginMessageTests.js
yarn.lock

**What:** Update discourse-node-api to 1.0.0.
Also, I'm making some small changes related to our LICENSE file
**Why:** Related to https://app.asana.com/0/1159164196409129/1167433009598523. This fixes the use of a deprecated API in Discourse that will stop working next April 20.
**How:**
- Update discourse-node-api to v1.0.0
- Introduce code changes required by the upgrade

Update discourse-node-api to 1.0.0

---

controllers/Admin/DisputesController.js
controllers/DisputesController.js

**What:** log using logger instead of console log. report errors to sentry 
**Why:** right now when we log the whole error, it outputs something that is hard to read in the logs. Since we are sending the error to Sentry and have all the error information there, by just having the message in the logs should be enough
**How:**
- Import `logger` and replace `console.error` for `logger.error`
- Add Sentry notification to caught errors

dev: log using logger instead of console log. report errors to sentry

---

views/dispute-tools/index.pug
views/home/dtr.pug

**What:** fix DOE link to borrower defense to repayment tool
**Why:** This broken link was reported by the dispute tools team
**How:**
- change URL for the right one

fix(dtr): fix doe link

---

views/includes/header.pug

**What:**
Use the correct link for the join the union header item
**Why:**
Closes: https://app.asana.com/0/1159164196409156/1199606858026341/f
**How:**
Replace the link for the `Join the union` item to redirect to the home page

Use correct link for join the union header item

---

HOW_TO.md
controllers/HomeController.js
services/messages/ContactUsEmail.js
views/home/contact.pug
views/messages/ContactUsEmail.ForAdmin.pug

**What:**
Add subject dropdown to the contact us form
**Why:**
Closes: https://app.asana.com/0/1159164196409129/1200001829300735/f
**How:**
- Add the dropdown in the pug template for the contact us page
- Catch the subject in the contact us request and include it in the email subject
https://www.loom.com/share/07e6107ddf0b45eca09f35df6c017d59

feat(contact-us): include a subject dropdown

---

src/stylesheets/base.css
src/stylesheets/components/Modal.css

**What:**
Push content below header
**Why:**
Closes: https://app.asana.com/0/1159164196409129/1200147097019351/f
**How:**
The header height changed from the previous header the app was using, by increasing the `header-heigth` css variable, the content was pushed below the header

Push content below header
