debtcollective/dispute-tools

lib/data/dispute-tools/constants.js

Make evidence documents required in Wage Garnishment and Tax Offset

---

config/config.sample.js
lib/discourse.js
migrations/20180329184303_add_unique_constraint_dispute_admins.js
models/Dispute.js
models/User.js
package.json
services/users.js
src/javascripts/components/admin/disputes/ManageDisputeAdmins.vue
src/javascripts/lib/api.js
tests/integration/controllers/Admin.DisputesControllerTest.js
tests/unit/models/Dispute.js
tests/utils/index.js
views/mixins/header-nav.pug
yarn.lock

This is great! On authentication we grab the user's information from Discourse. Below is an example of what we get back. This is still WIP as I need to fix the assign dispute admins functionality using the groups members query in the discourse-node-api to grab the members of the `dispute-admin` group.
Note that we don't store _any_ of this in our database. All we keep is the external id (the id in the data below) so that we can query for this stuff from the dispute tools.
```json
{
"id": 1,
"username": "marcondag",
"avatar_template": "/letter_avatar_proxy/v2/letter/m/53a042/{size}.png",
"active": true,
"admin": true,
"moderator": false,
"last_seen_at": "2018-03-28T23:03:16.201Z",
"last_emailed_at": null,
"created_at": "2018-03-17T17:37:33.737Z",
"last_seen_age": 555.50944, …
```

Retrieve user data from Discourse

---

config/RouteMappings.js
controllers/Admin/DisputesController.js
models/Attachment.js
models/DisputeRenderer.js
src/javascripts/components/admin/disputes/AdminShowFormInformationPanel.vue
tests/integration/controllers/Admin.DisputesControllerTest.js
tests/integration/controllers/DisputesControllerTest.js
tests/runner.js

Allow dispute admins to download dispute attachments in backoffice

---

config/RouteMappings.js
controllers/Admin/DisputesController.js
controllers/DisputesController.js
middlewares/flashMessages.js
models/Dispute.js
services/auth/tests.js
src/javascripts/components/Alerts.vue
src/javascripts/components/Attachment.vue
src/javascripts/components/admin/disputes/AdminShowFormInformationPanel.vue
src/javascripts/components/admin/disputes/ManageDisputeAdmins.vue
src/javascripts/lib/api.js
tests/integration/controllers/Admin.DisputesControllerTest.js
tests/utils/index.js

Add administrator dispute attachment CRUD

---

lib/assets/document_templates/general_debt_dispute_letter/0.pug
lib/data/form-definitions/shared-fields/debtAmount.js
services/formValidation.js

[Example PDF](https://github.com/debtcollective/dispute-tools/files/1948894/general_dispute_letter-8b6ae62c-e263-4528-b59e-65625e904252.pdf)

Fix general debt dispute letter formatting

---

README.md
controllers/Admin/DisputesController.js
lib/data/form-definitions/constants.js
views/admin/disputes/index.pug

https://github.com/debtcollective/parent/issues/75
The top example is what it looks like when the name field isn't filled out yet.

Display debtors' names in admin disputes index page

---

config/config.sample.js

Makes setting up a dev environment even easier.

better defaults in the config

---

views/disputes/show.pug
views/includes/disputes/information-form.pug

https://github.com/debtcollective/parent/issues/59#issuecomment-385203717

remove X, emphasize save button

---

views/admin/disputes/index.pug

https://github.com/debtcollective/parent/issues/125

show student name when debtor is a student

---

middlewares/cors.js
middlewares/handleAuthentication.js
services/sso.js
views/includes/header.pug

addresses https://github.com/debtcollective/parent/issues/146 and https://github.com/debtcollective/parent/issues/145

Pass correct login link to header config

---

src/lib/kabinett/components/button.css
src/stylesheets/_entries/admin/disputes/show.css
src/stylesheets/_entries/dispute-tools/show.css
src/stylesheets/_entries/disputes/show.css
src/stylesheets/utils.css
views/admin/disputes/index.pug
views/includes/disputes/process.pug
views/includes/header.pug
views/shared/401.pug

This PR fixes issues with css/html in the tools
Closes https://github.com/debtcollective/parent/issues/166

Small css fixes

---

src/javascripts/components/disputes/InformationForm.js
src/stylesheets/_entries/disputes/show.css
src/stylesheets/utils.css

The assert error message was completely unrelated but I fixed it anyway.
https://github.com/debtcollective/parent/issues/176

Chrome form validation on radio buttons works

---

controllers/Admin/DisputesController.js
models/DisputeStatus.js
package.json
scripts/test/form-validations
scripts/test/index
scripts/test/integration
scripts/test/unit
src/javascripts/components/admin/disputes/AdminDisputesAddStatusForm.js
tests/runner.js
tests/unit/models/DisputeStatus.js
views/includes/admin/disputes/add-status-form.pug
views/includes/header.pug
yarn.lock

Resolves https://github.com/debtcollective/parent/issues/204
Also adds the [chai-as-promised](https://www.chaijs.com/plugins/chai-as-promised/) library to clean up async test assertions.

Update admin status view

---

controllers/DisputesController.js
models/Dispute.js
models/DisputeRenderer.js

Resolves https://github.com/debtcollective/parent/issues/63

Prevent duplicate success/error messages

---

controllers/HomeController.js
src/javascripts/components/DonationFlow.js
views/includes/donation-flow.pug

This PR fixes the donation flow. I'll port the fix for the focus issue described in debtcollective/parent#227 to https://gitlab.com/debtcollective/debtcollective.
I'm making the least amount of changes needed, but this component needs to be redone.
Closes debtcollective/parent#227
**success**
**fail**
**success with donation**
**email**

fixing donation flow

---

src/javascripts/_entries/dispute-tools/index.js
src/javascripts/components/disputes/DebtAmounts.vue
src/stylesheets/base.css
views/includes/header.pug
views/layouts/application.pug

- Adding placeholder to debt type select
- Fixing "Why file a dispute" scroll to element
- moving header out of `<main>`

Adding placeholder to debt type select

---

package.json
src/javascripts/components/Alerts.vue
src/javascripts/components/admin/disputes/AdminShowFormInformationPanel.vue
views/layouts/application.pug

- Removes `getUserByExternalId` call from the Dispute details modal
- Change favicon to point s3 bucket
- adds `yarn minio` command to run minio with default parameters

removing getUserByExternalId call

---

services/renderers/tool-configurations/credit-report-dispute-letter.js

- Changing TransUnion address in credit report tool
Closes debtcollective/parent#259

changing credit report letter address

---

seeds/20171113114842_dispute_tools.js

- Updating Credit Report description
Closes debtcollective/parent#258

updating Credit Report description

---

config/RouteMappings.js
controllers/HomeController.js

This PR adds a redirection from `/donate` to `/?donate`, this is used to open the donation modal in the root page of the tools application.
Closes debtcollective/parent#263

redirect /donate to /?donate

---

migrations/20181207200320_add_more_profile_fields.js
models/User.js
src/javascripts/components/admin/disputes/AdminShowFormInformationPanel.vue
views/includes/footer.pug
views/includes/header.pug
yarn.lock

This PR adds `zip`, `state` and `phone_number` fields to the `Users` table. Also, changes **Campaigns** link in the header and footer to **Community**

Adding profile files to Users table

---

HOW_TO.md
Makefile
config/middlewares.js
controllers/DisputeToolsController.js
controllers/DisputesController.js
controllers/HomeController.js
controllers/SessionsController.js
lib/core/raven.js
lib/core/sentry.js
lib/index.js
lib/passport/discourse.js
middlewares/SentryError.js
middlewares/SentryRequest.js
middlewares/raven-error.js
middlewares/raven-request.js
models/Dispute.js
package.json
services/messages/DebtCollectiveMessage.js
services/messages/DiscourseMessage.js
views/layouts/admin.pug
views/layouts/application.pug
views/layouts/donate.pug
yarn.lock

- Adds Sentry to front-end
- Migrates from Raven to Sentry SDK
Closes debtcollective/parent#230

upgrading sentry library and adding it to the front-end

---

config/config.sample.js
views/includes/analytics.pug
views/layouts/admin.pug
views/layouts/application.pug
views/layouts/donate.pug

- Adding GA to front-end
Closes debtcollective/parent#231

adding ga to front-end

---

shared/enum/DisputeStatuses.js
views/includes/admin/disputes/add-status-form.pug

- Adding new admin statuses for Disputes.
- Cold Case
- Resolved
- Research Needed
- Active Legal

adding new statuses

---

models/Dispute.js
package.json
src/javascripts/components/admin/disputes/AdminShowFormInformationPanel.vue
views/admin/disputes/index.pug
yarn.lock

- Allow admins to search in all personal information fields in a Dispute. ex. SSN, name, phone number, city, etc.

search in Dispute personal-information data in admin backend

---

src/javascripts/_entries/dispute-tools/index.js
views/home/dtr.pug

- Fixing copy in DTR page
- Adding ga tracking to external DTR website

chore(DTR): tracking external clicks in ga

---

README.md

After a fresh install I notice that there is some information that needs to be clear, so I have added to the README.

docs(Clarify some settings to make sure CORS + SSO works as expected):

---

src/javascripts/components/disputes/InformationForm.js

Fix for InformationForm, make sure to check https://github.com/debtcollective/dispute-tools/issues/141#issuecomment-464829880
Closes #141

Prevent to use forEach over NodeList as it doesn't have solid cross browser support

---

.gitlab-ci.yml
package.json
src/javascripts/components/disputes/InformationForm.js
src/stylesheets/_entries/disputes/show.css
src/stylesheets/components/Modal.css
views/disputes/show.pug
views/includes/disputes/information-form.pug
views/layouts/admin.pug
views/layouts/application.pug
views/layouts/donate.pug
views/layouts/placeholder.pug
yarn.lock

This PR fixes two issues in mobile devices
- Validations on dates were broken in mobile devices
- Scrolling wasn't smooth on touch devices
Fixes #159 
**validations and scrolling**
[gif](http://recordit.co/DLs4h8NPoE)

Fixing dispute form validations and overflow issues on mobile

---

seeds/20171113114842_dispute_tools.js

feat(seeds): change psl about text [ci skip]

---

models/Dispute.js
views/admin/disputes/index.pug

**What:** adding type="number" to ID filter in the admin backend
**Why:** Fixes #168 
**How:** adding the type in the HTML field. Also, we are doing a basic number check in the backend just to be sure this error doesn't happen again.

fix(DisputeAdmin): adding type="number" to ID field

---

.gitlab-ci.yml
src/javascripts/components/DonationFlow.js

**What:** Building and pushing docker images in CI
**Why:** Close #178 
**How:** Adding two new stages to CI configuration, `build` and `deploy`
- There's a commit that was left out from my last PR

CI to build docker images

---

.gitlab-ci.yml

**What:** Pass docker image as artifacts from build stage to deploy
**Why:** to have the image available in the deploy stage
**How:** using `docker save` and `docker load`

dev: use artifacts to pass image to deploy stage

---

src/stylesheets/utils.css
views/disputes/my.pug

**What:** show creditor name in My Disputes list
**Why:** Related to https://app.asana.com/0/1159164196409226/1164791584968881, Closes #187 
**How:**
- Remove Dispute user name
- Add creditor name to list

feat(disputes): show creditor name in My Disputes list

---

package.json
services/messages/DiscourseMessage.js
tests/unit/messages/DiscourseMessageTests.js
yarn.lock

**What:** Fix autoresponder
**Why:** Closes https://app.asana.com/0/1168997577035609/1179448257485197
Related to https://github.com/debtcollective/discourse-node-api/pull/18
**How:**
- Change `target_usernames` to `target_recipients`
- Upgrade discourse-node-api to 1.0.1

Fix autoresponder

---

Dockerfile
Makefile
README.md
config/config.sample.js
config/middlewares.js
controllers/DisputesController.js
controllers/SessionsController.js
middlewares/cookies.js
middlewares/currentUser.js
middlewares/sessions.js
models/User.js
package.json
services/auth/authentication.js
services/sso.js
tests/integration/controllers/DisputesControllerTest.js
tests/integration/controllers/SessionsControllerTest.js
tests/unit/services/sso.test.js
tests/utils/index.js
views/includes/header.pug
views/layouts/admin.pug
views/layouts/application.pug
yarn.lock

**What:** Integrate dc-header component
https://www.loom.com/share/b6c2379478d341189077b11b4dd68e75
**Why:** Closes https://app.asana.com/0/1196225495304457/1196365498597561
**How:**
This is at a high level how this works. Is what `sso.js` implements
- Add dc-header package using jsdelivr
- render dc-header in application layout
- change how we get currentUser to use Discourse sso cookie

Integrate dc-header component

---

src/stylesheets/base.css
src/stylesheets/components/Footer.css
views/includes/footer.pug

**What:**
Set footer at the bottom of the page regardless of the amount of content
**Why:**
Closes: https://app.asana.com/0/1159164196409156/1187007774305281/f
**How:**
- Add an `absolute` position to the footer
https://www.loom.com/share/aa21a5d45e154c3cb3a8a6ce93a6d3d2

fix(footer): set footer at the bottom of the page regardless of the amount of content

---

views/includes/header.pug
views/layouts/admin.pug
views/layouts/application.pug

**What:**
Update the header component version
**Why:**
Relates to: https://app.asana.com/0/1159164196409156/1195530778765025/f
**How:**
Updating the links from jsdelivr to get the version @2.1.4 of the header component
https://www.loom.com/share/802a5e8b2a4a4b5d8a0e7a9cdab1438f

Update header component version

---

views/dispute-tools/index.pug
views/home/contact.pug
views/includes/footer.pug

**What:**
Add a legal disclaimer to the dispute tools
**Why:**
Closes: https://app.asana.com/0/1159164196409129/1199960314973457/f
**How:**
Add label mentioned in the task description

feat(home): add legal disclaimer below tools list

---

views/includes/header.pug
views/layouts/admin.pug
views/layouts/application.pug

**What:**
Update header component package version
**Why:**
Relates to: https://app.asana.com/0/1159164196409129/1194694158783964/f
**How:**
Updating package locally

Update the header component version

---

lib/assets/document_templates/general_debt_dispute_letter/0.pug
services/renderers/tool-configurations/general-dispute-letter.js

**What:**
Update the General dispute letter with new copy
**Why:**
closes https://app.asana.com/0/1168997577035609/1200147097019347
**How:**
Use the ticket attached document and replace respective document template
**Media:**

Update general dispute letter

---

views/includes/header.pug
views/layouts/admin.pug
views/layouts/application.pug

**What:**
Update our custom header
**Why:**
Part of initiative to offer a unify UX across all spaces
**How:**
Make the CDN to point to latest version of the header
**Media:**

feat(header): update to latest version
